/**
 * What the database calls a thing, and what a person calls it.
 *
 * Every state on this platform is a string in a CHECK constraint —
 * `PARTIALLY_PAID`, `READY_FOR_REVIEW`, `FARMERS_COOPERATIVE` — and both
 * front ends rendered them by taking the underscores out. That is English
 * whatever language the app is set to, and it is not always good English
 * either: an officer working in Hausa read "partially paid" and "farmers
 * cooperative" in the middle of Hausa sentences, and a status badge is
 * exactly the place somebody looks when they are in a hurry.
 *
 * WHY KEYED BY VALUE RATHER THAN BY COLUMN. The same word means the same
 * thing wherever it appears: a PENDING device and a PENDING refund are both
 * waiting, and the badge sits beside the noun that says which. Keying by
 * `table.column` would triple the dictionary to say "Ana jira" three times,
 * and every one of those copies could drift from the others. If a value ever
 * does need different words in two places, this is where that exception
 * would be written down, and it would be visible.
 *
 * `check-enum-labels.test.ts` reads the CHECK constraints out of the live
 * schema and fails if any allowed value is missing from this map, so a state
 * added to the database tomorrow cannot reach a screen in English.
 */

import type { TranslationDictionary } from './i18n';

export const ENUM_LABELS: Record<string, keyof TranslationDictionary> = {
  "A": 'enumClassA',
  "ABANDONED": 'enumAbandoned',
  "ABORTED": 'enumAborted',
  "ACCEPTED": 'enumAccepted',
  "ACCOUNT_TRANSFER": 'enumAccountTransfer',
  "ACTION_REQUIRED": 'enumActionRequired',
  "ACTIVATED": 'enumActivated',
  "ACTIVE": 'enumActive',
  "ADDITIONAL_IDENTIFICATION": 'enumAdditionalIdentification',
  "ADDITIVE_BENEFIT": 'enumAdditiveBenefit',
  "ADMINISTRATION": 'enumAdministration',
  "AGENT": 'enumAgent',
  "AGENT_ACTIVATION": 'enumAgentActivation',
  "AGENT_ACTIVITY": 'enumAgentActivity',
  "AGENT_ASSISTED": 'enumAgentAssisted',
  "AGENT_CONDUCT": 'enumAgentConduct',
  "AGENT_MISCONDUCT": 'enumAgentMisconduct',
  "AGENT_ONBOARDING": 'enumAgentOnboarding',
  "AGENT_OVERRIDE_ACTIVATION": 'enumAgentOverrideActivation',
  "AGENT_PWA": 'enumAgentPwa',
  "AGENT_SUSPENSION": 'enumAgentSuspension',
  "AGREED": 'enumAgreed',
  "AGREEMENT_ACCEPTED": 'enumAgreementAccepted',
  "AGRICULTURE": 'enumAgriculture',
  "AGRICULTURE_PROCESSING": 'enumAgricultureProcessing',
  "AMOUNT_MISMATCH": 'enumAmountMismatch',
  "ANNUAL": 'enumAnnual',
  "ANOMALY": 'enumAnomaly',
  "API": 'enumApi',
  "APPLICATION_SUBMITTED": 'enumApplicationSubmitted',
  "APPROVAL": 'enumApproval',
  "APPROVAL_WAITING": 'enumApprovalWaiting',
  "APPROVED": 'enumApproved',
  "ARCHIVED": 'enumArchived',
  "ARTISAN_CRAFT": 'enumArtisanCraft',
  "ARTISAN_GUILD": 'enumArtisanGuild',
  "ASSERTED": 'enumAsserted',
  "ASSESSED": 'enumAssessed',
  "ASSESSMENT": 'enumAssessment',
  "ASSESSMENT_CREATED": 'enumAssessmentCreated',
  "ASSIGNED": 'enumAssigned',
  "ATTESTATION": 'enumAttestation',
  "ASSIGNMENT": 'enumAssignment',
  "ATTESTED": 'enumAttested',
  "AUDIT": 'enumAudit',
  "AUDIT_SAMPLE": 'enumAuditSample',
  "AUTHORITY_LOOKUP": 'enumAuthorityLookup',
  "AUTO_RECOMMENDATION": 'enumAutoRecommendation',
  "AWAITING_INFORMATION": 'enumAwaitingInformation',
  "AWARDED": 'enumAwarded',
  "B": 'enumClassB',
  "BAG_25KG": 'enumBag25kg',
  "BAG_50KG": 'enumBag50kg',
  "BANK_ACCOUNT_CHANGE": 'enumBankAccountChange',
  "BANK_CHANGE_APPLIED": 'enumBankChangeApplied',
  "BANK_CHANGE_REFUSED": 'enumBankChangeRefused',
  "BANK_CHANGE_REQUESTED": 'enumBankChangeRequested',
  "BANK_TRANSFER": 'enumBankTransfer',
  "BANK_VERIFIED": 'enumBankVerified',
  "BASE": 'enumBase',
  "BLOCKED": 'enumBlocked',
  "BOOKS": 'enumBooks',
  "BOTH": 'enumBoth',
  "BUILDING": 'enumBuilding',
  "BUSINESS": 'enumBusiness',
  "BUSINESS_OBSERVATION": 'enumBusinessObservation',
  "BVN": 'enumBvn',
  "C": 'enumClassC',
  "CAMERA": 'enumCamera',
  "CANCELLED": 'enumCancelled',
  "CARD": 'enumCard',
  "CASE_ASSIGNED": 'enumCaseAssigned',
  "CASE_ESCALATED": 'enumCaseEscalated',
  "CASE_MENTION": 'enumCaseMention',
  "CATEGORY": 'enumCategory',
  "CIVIL_SERVANT": 'enumCivilServant',
  "CITIZEN_STATEMENT": 'enumCitizenStatement',
  "CLEAN": 'enumClean',
  "CLEARED": 'enumCleared',
  "CLOSED": 'enumClosed',
  "CLOSING": 'enumClosing',
  "COLLECTED": 'enumCollected',
  "COLLECTION": 'enumCollection',
  "COMMENT": 'enumComment',
  "COMMISSION": 'enumCommission',
  "COMMISSION_ADJUSTMENT": 'enumCommissionAdjustment',
  "COMMISSION_ANOMALY": 'enumCommissionAnomaly',
  "COMMISSION_PAYOUT": 'enumCommissionPayout',
  "COMMISSION_QUERY": 'enumCommissionQuery',
  "COMMUNITY_LEADER": 'enumCommunityLeader',
  "COMPLETED": 'enumCompleted',
  "CONFIRMED": 'enumConfirmed',
  "CONFIRMED_BY_TAXPAYER": 'enumConfirmedByTaxpayer',
  "CONJUNCTIVE": 'enumConjunctive',
  "CONSISTENCY_CHECK": 'enumConsistencyCheck',
  "CONSTRUCTION": 'enumConstruction',
  "COVERAGE_LEAD": 'enumCoverageLead',
  "CRITICAL": 'enumCritical',
  "D": 'enumClassD',
  "DAILY": 'enumDaily',
  "DATA_CHANGE": 'enumDataChange',
  "DATA_CORRECTION": 'enumDataCorrection',
  "DEGRADED": 'enumDegraded',
  "DELIVERED": 'enumDelivered',
  "DENIED": 'enumDenied',
  "DEPARTMENT": 'enumDepartment',
  "DEVICE": 'enumDevice',
  "DEVICE_VELOCITY": 'enumDeviceVelocity',
  "DISAGREED": 'enumDisagreed',
  "ENUMERATION": 'enumEnumeration',
  "FACTS_WRONG": 'enumFactsWrong',
  "FILED": 'enumFiled',
  "HAS_RECORDS": 'enumHasRecords',
  "KIOSK": 'enumKiosk',
  "LOCK_UP_SHOP": 'enumLockUpShop',
  "MICRO": 'enumMicro',
  "NANO": 'enumNano',
  "NONE": 'enumNone',
  "NOT_SOUGHT": 'enumNotSought',
  "NOT_TRADING": 'enumNotTrading',
  "OBJECTED": 'enumObjected',
  "PRESUMPTIVE": 'enumPresumptive',
  "SHARED_PHONE_NUMBER": 'enumSharedPhoneNumber',
  "DUPLICATE_TAXPAYER_DETAILS": 'enumDuplicateTaxpayerDetails',
  "OUT_OF_TERRITORY": 'enumOutOfTerritory',
  "REPEATED_FAILED_PAYMENTS": 'enumRepeatedFailedPayments',
  "REVERSAL_PATTERN": 'enumReversalPattern',
  "SMALL": 'enumSmall',
  "STALL": 'enumStall',
  "TAXPAYER_REQUEST": 'enumTaxpayerRequest',
  "TURNOVER_GOVERNED": 'enumTurnoverGoverned',
  "UNUSUAL_VOLUME": 'enumUnusualVolume',
  "RAPID_SUCCESSION": 'enumRapidSuccession',
  "SETTLEMENT_VARIANCE": 'enumSettlementVariance',
  "DEVICE_REGISTERED": 'enumDeviceRegistered',
  "DISMISSED": 'enumDismissed',
  "DISPUTED": 'enumDisputed',
  "DOCUMENT": 'enumDocument',
  "DOCUMENT_CAPTURE": 'enumDocumentCapture',
  "DOWN": 'enumDown',
  "DOWNLOAD": 'enumDownload',
  "DRAFT": 'enumDraft',
  "DRAWN": 'enumDrawn',
  "DRIVERS_LICENCE": 'enumDriversLicence',
  "DUE_DATE_CHANGE": 'enumDueDateChange',
  "DUPLICATE": 'enumDuplicate',
  "DUPLICATE_PAYMENT": 'enumDuplicatePayment',
  "EDUCATION": 'enumEducation',
  "ELIGIBILITY_GATE": 'enumEligibilityGate',
  "ELIGIBLE": 'enumEligible',
  "EMAIL": 'enumEmail',
  "EMPLOYER": 'enumEmployer',
  "ENFORCEMENT": 'enumEnforcement',
  "ENTERTAINMENT_ARTS": 'enumEntertainmentArts',
  "ESCALATED": 'enumEscalated',
  "ESCALATION": 'enumEscalation',
  "EVIDENCE": 'enumEvidence',
  "EXCEPTION": 'enumException',
  "EXECUTED": 'enumExecuted',
  "EXISTING": 'enumExisting',
  "EXPIRED": 'enumExpired',
  "FAILED": 'enumFailed',
  "FAILURE": 'enumFailure',
  "FARMERS_COOPERATIVE": 'enumFarmersCooperative',
  "FEDERAL": 'enumFederal',
  "FEMALE": 'enumFemale',
  "FILE": 'enumFile',
  "FINANCE": 'enumFinance',
  "FINANCIAL_SERVICES": 'enumFinancialServices',
  "FISHERIES_GROUP": 'enumFisheriesGroup',
  "FISHING": 'enumFishing',
  "FIXED": 'enumFixed',
  "FOOD_BEVERAGE": 'enumFoodBeverage',
  "FORFEITED": 'enumForfeited',
  "FORMULA": 'enumFormula',
  "FORTNIGHTLY": 'enumFortnightly',
  "FOUND": 'enumFound',
  "FOUR_TO_ELEVEN": 'enumFourToEleven',
  "FRAUD_FLAG": 'enumFraudFlag',
  "FRAUD_INVESTIGATION": 'enumFraudInvestigation',
  "FREQUENT_MANUAL_INTERVENTION": 'enumFrequentManualIntervention',
  "FULL": 'enumFull',
  "GAMING_BETTING": 'enumGamingBetting',
  "GATEWAY": 'enumGateway',
  "GATEWAY_WEBHOOK": 'enumGatewayWebhook',
  "GENERAL": 'enumGeneral',
  "GENERATED": 'enumGenerated',
  "GOVERNMENT": 'enumGovernment',
  "GOVERNMENT_APPROVED": 'enumGovernmentApproved',
  "GOVERNMENT_REJECTED": 'enumGovernmentRejected',
  "HEALTHCARE": 'enumHealthcare',
  "HIGH": 'enumHigh',
  "HIGHEST_VALUE": 'enumHighestValue',
  "HOTEL_HOSPITALITY": 'enumHotelHospitality',
  "ICT_TELECOMS": 'enumIctTelecoms',
  "IDENTITY_DOCUMENT": 'enumIdentityDocument',
  "IGNORED": 'enumIgnored',
  "INACTIVE": 'enumInactive',
  "INCORRECT_ASSESSMENT": 'enumIncorrectAssessment',
  "INDIVIDUAL": 'enumIndividual',
  "INFO": 'enumInfo',
  "INFORMAL_WORKER": 'enumInformalWorker',
  "INFO_REQUESTED": 'enumInfoRequested',
  "INITIATED": 'enumInitiated',
  "INSUFFICIENT_HISTORY": 'enumInsufficientHistory',
  "INTEGRATION_ALERT": 'enumIntegrationAlert',
  "INVALID": 'enumInvalid',
  "INVESTIGATING": 'enumInvestigating',
  "INVITED": 'enumInvited',
  "INVOICE": 'enumInvoice',
  "INVOICED": 'enumInvoiced',
  "INVOICE_GENERATED": 'enumInvoiceGenerated',
  "IN_PROGRESS": 'enumInProgress',
  "IN_REVIEW": 'enumInReview',
  "ISSUED": 'enumIssued',
  "ITEM": 'enumItem',
  "KILOGRAM": 'enumKilogram',
  "KYC_CLEARED": 'enumKycCleared',
  "KYC_FAILED": 'enumKycFailed',
  "KYC_INFO_REQUIRED": 'enumKycInfoRequired',
  "KYC_SUBMITTED": 'enumKycSubmitted',
  "LEFT": 'enumLeft',
  "LGA": 'enumLga',
  "LGA_PERFORMANCE": 'enumLgaPerformance',
  "LIMITED": 'enumLimited',
  "LINKED_EXISTING": 'enumLinkedExisting',
  "LITRE": 'enumLitre',
  "LIVESTOCK": 'enumLivestock',
  "LIVESTOCK_ASSOCIATION": 'enumLivestockAssociation',
  "LOCAL_GOVERNMENT": 'enumLocalGovernment',
  "LOGIN": 'enumLogin',
  "LOW": 'enumLow',
  "MALE": 'enumMale',
  "MANUAL": 'enumManual',
  "MANUAL_CORRECTION": 'enumManualCorrection',
  "MANUAL_ENTRY": 'enumManualEntry',
  "MANUAL_REVIEW": 'enumManualReview',
  "MANUFACTURING": 'enumManufacturing',
  "MARKET_ASSOCIATION": 'enumMarketAssociation',
  "MATCHED": 'enumMatched',
  "MEDIUM": 'enumMedium',
  "MERGED": 'enumMerged',
  "MIGRATION": 'enumMigration',
  "MINING": 'enumMining',
  "MISSING_PAYMENT": 'enumMissingPayment',
  "MISSING_PLATFORM_TRANSACTION": 'enumMissingPlatformTransaction',
  "MONTHLY": 'enumMonthly',
  "MOTOR_VEHICLE": 'enumMotorVehicle',
  "NEVER_CALLED": 'enumNeverCalled',
  "NIN": 'enumNin',
  "NORMAL": 'enumNormal',
  "NOTE": 'enumNote',
  "NOT_ATTEMPTED": 'enumNotAttempted',
  "NOT_AVAILABLE": 'enumNotAvailable',
  "NOT_FOUND": 'enumNotFound',
  "NOT_PERFORMED": 'enumNotPerformed',
  "NOT_REQUESTED": 'enumNotRequested',
  "NOT_STARTED": 'enumNotStarted',
  "OFFICE": 'enumOffice',
  "OFFICER": 'enumOfficer',
  "OFFICER_REVIEW": 'enumOfficerReview',
  "OFFLINE": 'enumOffline',
  "ONCE": 'enumOnce',
  "ONE_OFF": 'enumOneOff',
  "ONLINE": 'enumOnline',
  "ON_HOLD": 'enumOnHold',
  "OPEN": 'enumOpen',
  "OPENED": 'enumOpened',
  "OTHER": 'enumOther',
  "OVERRIDE_APPLIED": 'enumOverrideApplied',
  "PAID": 'enumPaid',
  "PARTIAL": 'enumPartial',
  "PARTIALLY_PAID": 'enumPartiallyPaid',
  "PASSED": 'enumPassed',
  "PASSPORT": 'enumPassport',
  "PASSPORT_PHOTOGRAPH": 'enumPassportPhotograph',
  "PASSWORD_RESET": 'enumPasswordReset',
  "PAYMENT_ACKNOWLEDGEMENT": 'enumPaymentAcknowledgement',
  "PAYMENT_EVIDENCE": 'enumPaymentEvidence',
  "PAYMENT_INITIATED": 'enumPaymentInitiated',
  "PAYMENT_ISSUE": 'enumPaymentIssue',
  "PAYMENT_PENDING": 'enumPaymentPending',
  "PAYMENT_RECONCILIATION": 'enumPaymentReconciliation',
  "PAYMENT_REVERSAL": 'enumPaymentReversal',
  "PAYMENT_SUCCESSFUL": 'enumPaymentSuccessful',
  "PAYMENT_VERIFIED": 'enumPaymentVerified',
  "PENDING": 'enumPending',
  "PENDING_ATTESTATION": 'enumPendingAttestation',
  "PENDING_PAYMENT": 'enumPendingPayment',
  "PENDING_SETTLEMENT": 'enumPendingSettlement',
  "PENDING_SYNC": 'enumPendingSync',
  "PERCENTAGE": 'enumPercentage',
  "PERIOD_CLOSING": 'enumPeriodClosing',
  "POLL": 'enumPoll',
  "PORTAL": 'enumPortal',
  "POS": 'enumPos',
  "POSTING": 'enumPosting',
  "PRIORITY_CHANGE": 'enumPriorityChange',
  "PRIVATE_EMPLOYEE": 'enumPrivateEmployee',
  "PROCEEDED": 'enumProceeded',
  "PROCESSED": 'enumProcessed',
  "PROCESSING": 'enumProcessing',
  "PROFESSIONAL_SERVICES": 'enumProfessionalServices',
  "PROOF_OF_ADDRESS": 'enumProofOfAddress',
  "PROPOSED": 'enumProposed',
  "PSIRS_SYNC": 'enumPsirsSync',
  "PUBLIC_SERVANT": 'enumPublicServant',
  "PUSH": 'enumPush',
  "QUARTERLY": 'enumQuarterly',
  "QUEUED": 'enumQueued',
  "RANDOM": 'enumRandom',
  "READ": 'enumRead',
  "READY_FOR_REVIEW": 'enumReadyForReview',
  "REAL_PROPERTY": 'enumRealProperty',
  "RECEIPT": 'enumReceipt',
  "RECEIPT_GENERATED": 'enumReceiptGenerated',
  "RECEIPT_ISSUE": 'enumReceiptIssue',
  "RECEIVED": 'enumReceived',
  "RECOGNISED_PROFESSIONAL": 'enumRecognisedProfessional',
  "RECONCILED": 'enumReconciled',
  "RECONCILIATION": 'enumReconciliation',
  "RECONCILIATION_EXCEPTION": 'enumReconciliationException',
  "RECONCILIATION_PENDING": 'enumReconciliationPending',
  "REFEREE": 'enumReferee',
  "REFEREE_CLEARED": 'enumRefereeCleared',
  "REFEREE_FAILED": 'enumRefereeFailed',
  "REFEREE_INVITED": 'enumRefereeInvited',
  "REFEREE_REPLACED": 'enumRefereeReplaced',
  "REFEREE_VERIFY": 'enumRefereeVerify',
  "REFUND": 'enumRefund',
  "REFUNDED": 'enumRefunded',
  "REGISTRATION": 'enumRegistration',
  "REINSTATED": 'enumReinstated',
  "REJECTED": 'enumRejected',
  "RELIGIOUS_LEADER": 'enumReligiousLeader',
  "RELIGIOUS_NGO": 'enumReligiousNgo',
  "REPEATED_RECEIPT_REGENERATION": 'enumRepeatedReceiptRegeneration',
  "REPLACED": 'enumReplaced',
  "REQUESTED": 'enumRequested',
  "RESOLUTION": 'enumResolution',
  "RESOLVED": 'enumResolved',
  "RESPONDED": 'enumResponded',
  "RETAIL_TRADE": 'enumRetailTrade',
  "RETIRED": 'enumRetired',
  "REVENUE_ANOMALY": 'enumRevenueAnomaly',
  "REVENUE_COLLECTION": 'enumRevenueCollection',
  "REVENUE_RATE_CHANGE": 'enumRevenueRateChange',
  "REVENUE_TARGET": 'enumRevenueTarget',
  "REVERSAL": 'enumReversal',
  "REVERSED": 'enumReversed',
  "REVIEW": 'enumReview',
  "REVIEWED": 'enumReviewed',
  "REVOKED": 'enumRevoked',
  "ROLE": 'enumRoleChange',
  "ROUTED": 'enumRouted',
  "RUNNING": 'enumRunning',
  "RUN_RATE": 'enumRunRate',
  "SEASONAL": 'enumSeasonal',
  "SEEDLING": 'enumSeedling',
  "SELFIE": 'enumSelfie',
  "SELF_ASSESSMENT": 'enumSelfAssessment',
  "SELF_EMPLOYED": 'enumSelfEmployed',
  "SENT": 'enumSent',
  "SERVICE_REQUEST": 'enumServiceRequest',
  "SETTLED": 'enumSettled',
  "SETTLEMENT": 'enumSettlement',
  "SHARE": 'enumShare',
  "SIGNED": 'enumSigned',
  "SMS": 'enumSms',
  "STARTED": 'enumStarted',
  "STATE": 'enumState',
  "STATUS_CHANGE": 'enumStatusChange',
  "STEP_UP": 'enumStepUp',
  "STUDENT_UNEMPLOYED": 'enumStudentUnemployed',
  "SUBMITTED": 'enumSubmitted',
  "SUCCEEDED": 'enumSucceeded',
  "SUCCESS": 'enumSuccess',
  "SUCCESSFUL": 'enumSuccessful',
  "SUPERSEDED": 'enumSuperseded',
  "SUPERVISOR": 'enumSupervisorChange',
  "SUPPORTING_DOCUMENT": 'enumSupportingDocument',
  "SUPPORT_TICKET": 'enumSupportTicket',
  "SUSPENDED": 'enumSuspended',
  "SYNCED": 'enumSynced',
  "SYSTEM": 'enumSystem',
  "SYSTEMATIC": 'enumSystematic',
  "SYSTEM_ALERT": 'enumSystemAlert',
  "SYSTEM_ISSUE": 'enumSystemIssue',
  "TAXPAYER": 'enumTaxpayer',
  "TAXPAYER_ADJUSTMENT": 'enumTaxpayerAdjustment',
  "TAXPAYER_COMPLAINT": 'enumTaxpayerComplaint',
  "TAXPAYER_DISPUTE": 'enumTaxpayerDispute',
  "TAXPAYER_REGISTRATION": 'enumTaxpayerRegistration',
  "TAXPAYER_SERVICES": 'enumTaxpayerServices',
  "TECHNICAL_ISSUE": 'enumTechnicalIssue',
  "TECHNOLOGY": 'enumTechnology',
  "TERRITORY": 'enumTerritory',
  "TIERED": 'enumTiered',
  "TIN_CONFIRMATION": 'enumTinConfirmation',
  "TIN_ISSUE": 'enumTinIssue',
  "TRACTOR_DAY": 'enumTractorDay',
  "TRADERS_ASSOCIATION": 'enumTradersAssociation',
  "TRADITIONAL_AUTHORITY": 'enumTraditionalAuthority',
  "TRAINING_COMPLETED": 'enumTrainingCompleted',
  "TRANSACTION": 'enumTransaction',
  "TRANSACTION_AUDIT": 'enumTransactionAudit',
  "TRANSPORT_HAULAGE": 'enumTransportHaulage',
  "TRANSPORT_PASSENGER": 'enumTransportPassenger',
  "TRANSPORT_UNION": 'enumTransportUnion',
  "TWELVE_OR_MORE": 'enumTwelveOrMore',
  "TWO_TO_THREE": 'enumTwoToThree',
  "UNAUTHORISED_CHARGE": 'enumUnauthorisedCharge',
  "UNAVAILABLE": 'enumUnavailable',
  "UNCHECKED": 'enumUnchecked',
  "UNDER_REVIEW": 'enumUnderReview',
  "UNIT": 'enumUnit',
  "UNKNOWN": 'enumUnknown',
  "UNPAID": 'enumUnpaid',
  "UNSPECIFIED": 'enumUnspecified',
  "UNUSUAL_OFFICER_ACTIVITY": 'enumUnusualOfficerActivity',
  "UNUSUAL_TRANSACTION_TIMING": 'enumUnusualTransactionTiming',
  "UNVERIFIED": 'enumUnverified',
  "UPHELD": 'enumUpheld',
  "UPLOAD": 'enumUpload',
  "URGENT": 'enumUrgent',
  "USER": 'enumUser',
  "USER_ACTIVITY": 'enumUserActivity',
  "USSD": 'enumUssd',
  "VALID": 'enumValid',
  "VEHICLE": 'enumVehicle',
  "VEHICLE_CAPTURE": 'enumVehicleCapture',
  "VEHICLE_ISSUE": 'enumVehicleIssue',
  "VEHICLE_RENEWAL": 'enumVehicleRenewal',
  "VERIFICATION_REQUIRED": 'enumVerificationRequired',
  "VERIFIED": 'enumVerified',
  "VERIFY": 'enumVerify',
  "VIEW": 'enumView',
  "VOTERS_CARD": 'enumVotersCard',
  "WAIVED": 'enumWaived',
  "WARNING": 'enumWarning',
  "WEBHOOK": 'enumWebhook',
  "WEEKLY": 'enumWeekly',
  "WHATSAPP": 'enumWhatsapp',
  "WHOLESALE_TRADE": 'enumWholesaleTrade',
  "WITHDRAWN": 'enumWithdrawn',
  "admin": 'enumAdmin',
  "agent": 'enumAgent',
  "auditor": 'enumAuditor',
  "en": 'enumEn',
  "finance_officer": 'enumFinanceOfficer',
  "ha": 'enumHa',
  "revenue_officer": 'enumRevenueOfficer',
  "supervisor": 'enumSupervisor',
};

/**
 * The exceptions the note above promised would be written down here.
 *
 * Keyed by the column the value came from, and holding only values that
 * genuinely mean different things in different places. Every entry costs a
 * second word in the dictionary and a call site that has to remember to say
 * where it is, so the bar is that the shared word is *wrong*, not merely that
 * a different one might read better.
 *
 * `taxpayers.tin_status` is the first. `ASSIGNED` is `An ba wa wani` — *given
 * to someone* — which is right for a case handed to an officer and wrong for
 * a Tax Identification Number, where the whole point is that the number has
 * been issued to the person reading the screen. On the citizen page it told
 * somebody their own TIN belonged to somebody else. `An bayar` — *issued* —
 * follows `An nema` (requested) the way the English does.
 *
 * The English is deliberately unchanged: "Assigned" is right for a TIN, and
 * an exception that quietly rewrote the English too would hide what this is.
 */
export const ENUM_LABEL_EXCEPTIONS: Record<
  string,
  Record<string, keyof TranslationDictionary>
> = {
  'taxpayers.tin_status': { ASSIGNED: 'enumTinAssigned' },
};

/**
 * The name a person reads for a database value.
 *
 * A value the map does not know still has to read as something — a screen
 * that renders an empty string where a status belongs is worse than one that
 * renders an unfamiliar word — so the fallback is the value with its
 * underscores taken out, which is what every call site used to do. It is the
 * old behaviour kept for exactly the case the check above is designed to stop
 * reaching production.
 *
 * `column` names where the value came from, as `table.column`. Pass it only
 * where the answer differs from the shared one; leaving it off is right
 * everywhere else and is what nearly every call site does.
 */
export function enumLabel(
  value: string | null | undefined,
  t: TranslationDictionary,
  column?: string,
): string {
  if (!value) return '';
  const exception = column ? ENUM_LABEL_EXCEPTIONS[column]?.[value] : undefined;
  if (exception) return t[exception];
  const key = ENUM_LABELS[value];
  if (key) return t[key];
  return value.replace(/_/g, ' ').toLowerCase();
}
